### ISSUE TITLE
12 - videopatch stalls when both VideoToTexture nodes are connected at the same time

### ISSUE THREAD

**Issue by mhusinsky** [chkworks/VL.TheBigBang#54]
when opening patch 12 (video & camera input), both VideoToTexture nodes are connected to the same  source. this apparently stalls the patch and it is not usable (effect is obvious to see when just opening the patch)

![grafik](https://github.com/user-attachments/assets/60cd62e0-8a69-4fcd-ab13-bf7a68ae7f41)

this is on gamma stable 6.6

the patch should probably not connect both by default

**Comment by animanoir** [comment]
Happens to me too.

**Comment by chkworks** [comment]
Thank you both for the report, fixed in version 6.1.2!
