### ISSUE TITLE
`VideoSourceToTexture` seems to render nothing (12. Video and Camera input)

### ISSUE THREAD

**Issue by animanoir** [chkworks/VL.TheBigBang#55]
![image](https://github.com/user-attachments/assets/012b49d0-4d6a-4d86-a09f-2f04c79a804a)

Also the webcam video doesn't shows up, and when enabled, it slows the patch to dead.

**Comment by chkworks** [comment]
Also fixed in 6.1.2, thanks!

**Comment by animanoir** [comment]
thanks! still new to vvvv—what is the command to update the version of the VL.TheBigBang?

**Comment by chkworks** [comment]
Just the same installation command again, it will install the newest version.

`nuget install VL.TheBigBang`
